import { corsHeaders, handleCors } from "../_shared/cors.ts";
import { extractJwt, resolveUserProfile } from "../_shared/auth.ts";

const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY") || "";

const SYSTEM_PROMPT = `You are a compliance and quality-assurance audit assistant for an Australian fencing supplier (SkybrookAI/Glass Outlet).
Your task is to take a fence design payload (CanonicalPayload) and the generated Bill of Materials (BOM) items, and return structured audit feedback.

Focus areas:
1. Australian Pool Fencing Compliance (AS1926.1):
   - Pool fencing must be at least 1200mm high.
   - Gaps under the fence or between vertical/horizontal members must not exceed 100mm.
   - Pool gates must open OUTWARDS (away from the pool area).
   - Pool gate latches must be at least 1500mm above finished ground level, or shielded on the inside if lower.
   
2. Structural / Span limits:
   - QuickScreen horizontal slat panels (QSHS) have a maximum stock width of 2600mm. Spans exceeding 2600mm without intermediate posts are structural failures and must be split.
   - Vertical slat panels (VS) have a maximum width recommendation of 2000mm.
   
3. Gate Limits:
   - Single swing gates over 1200mm wide put severe load on hinges. Warn and recommend double swing or sliding configurations for single openings > 1200mm.
   - Single swing gates must not exceed 2100mm opening width.
   - Double swing gates must not exceed 4200mm opening width.
   
4. Accessory checklist suggestions:
   - If colorbond colors (e.g. Monument, Surfmist, Black Satin) are used, suggest color-matching touch-up paint.
   - Suggest magnetic driver bits for self-drilling screw installation.
   - Suggest core drill tooling, grout, or chemical anchors if base-plated or core-drilled post mounting is chosen.

Output Schema (must be valid JSON):
[
  {
    "type": "compliance" | "warning" | "suggestion",
    "severity": "error" | "warning" | "info",
    "message": "Clear, actionable message with recommendations or warnings, detailing which runs/gates it applies to."
  }
]

Provide feedback strictly as a JSON array of objects. Do not include markdown code block formatting (like \`\`\`json), leading text, or trailing comments.
`;

Deno.serve(async (req: Request) => {
  const cors = handleCors(req);
  if (cors) return cors;

  try {
    const jwt = extractJwt(req);
    await resolveUserProfile(jwt);

    const body = await req.json();
    const { payload, bomItems } = body;

    if (!payload || !bomItems) {
      throw new Error("Missing payload or bomItems in request body");
    }

    if (!GEMINI_API_KEY) {
      throw new Error("Server configuration error: GEMINI_API_KEY is not set.");
    }

    const promptText = `
${SYSTEM_PROMPT}

---
FENCE DESIGN PAYLOAD (JSON):
${JSON.stringify(payload, null, 2)}

---
GENERATED BOM ITEMS (JSON):
${JSON.stringify(bomItems, null, 2)}

---
Run compliance and quality audit, and output JSON list of review findings:
`;

    // Call Gemini 1.5 Pro for advanced reasoning
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              role: "user",
              parts: [
                {
                  text: promptText,
                },
              ],
            },
          ],
          generationConfig: {
            responseMimeType: "application/json",
            temperature: 0.1,
          },
        }),
      },
    );

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`Gemini API error: ${response.status} - ${errText}`);
    }

    const result = await response.json();
    const textOutput = result?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!textOutput) {
      throw new Error("No response generated by Gemini model.");
    }

    const parsedData = JSON.parse(textOutput.trim());

    return new Response(JSON.stringify(parsedData), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 200,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return new Response(JSON.stringify({ error: message }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 400,
    });
  }
});
